apiVersion: v1
kind: Service
metadata:
  name: nextjs-csr-app-service
  labels:
    app: nextjs-csr-app
spec:
  type: LoadBalancer
  selector:
    app: nextjs-csr-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
